mathiazom/rezervo-web

components/ClassCard/ClassCard.tsx, components/Schedule.tsx
Make it possible to link to the info pages for different classes. The link uses the `id` to determine which class has been linked to, and looks like this:
`http://localhost:3000/?id=123455`
If the link is invalid, it is quietly ignored, and all classes are displayed as normal. In the future it would be cool to display a toast with a little message that the link you entered has invalid data.
This PR also refactored out the class info modal from `ClassCard` to `Schedule`, with the same approach as the `auth` branch.
=> Class Info Links

lib/iBooking.ts
With this change, all events for the current date is displayed, even those events that are in the past. This makes it possible to not display next weeks day. For instance, currently if today is Thursday, sit-rezervo will show two entries for Thursday, namely this one, and the next. Now, it only shows this Thursday. 
This removes duplication of events in the calendar, and makes it easier to understand (at least in my head)
Before
After
=> fix: display all of today's events instead of one week ahead of time

components/Schedule.tsx
This mostly applies to widescreen users.
Before
After
=> style(Schedule): horizontally align to center

components/AppBar.tsx, components/ClassCard/ClassCard.tsx, components/ClassInfo.tsx, components/MobileConfigUpdateBar.tsx, components/Schedule.tsx, lib/iBooking.ts, lib/popularity.ts, package.json, pages/_app.tsx, pages/api/schedule.ts, pages/index.tsx, types/derivedTypes.ts, utils/timeUtils.ts, yarn.lock
With these changes, it is now possible to navigate between weeks. Each week starts with a Monday, and you always load into the current week. This weeks schedule, along with one week in the past and three weeks in the future are cached on static site generation. If the user wants to go to different weeks, these are loaded in as we go.
Classes that are in the past have lower opacity, and have strike through in their titles. In addition, popularity is hidden, since that does not make sense for a class that is in the past.
Ended up having to use the Luxon time library to determine week numbers, since the standard date library was not sufficient. (And Dayjs did not handle years with 53 weeks well) 
Before
After
https://github.com/mathiazom/sit-rezervo-confgen/assets/26925695/1c6e4694-64d3-4e8d- …
=> Implement Week Navigation

components/PageHead.tsx, pages/index.tsx
To make it easy to create more pages with different titles, but the same favicons. This is useful for future work in generalizing `sit-rezervo-confgen`
=> refactor(index): extract common head elements

components/AppBar.tsx, components/MobileConfigUpdateBar.tsx, components/Schedule.tsx, pages/index.tsx
With this PR, I do some cleanup in terms of moving logic that is only used (or wrapped around) a component into said component. This is to hide that components specific display and styling from the index file. No logic changes here, only moving wrapping elements (thus resulting in huge diffs, but in reality it is mostly indenting) It is therefore easiest to see the changes by going commit by commit. 
Again, a small stepping stone into generalising `sit-rezervo-confgen`
=> Move Component Specific Logic From Index To Their Respective Components

components/modals/AgendaModal.tsx, components/modals/ClassInfoModal.tsx, components/modals/SettingsModal.tsx, pages/index.tsx
With this PR, I extract the logic for the Modals in Index.tsx to separate components. This is a small step in the larger task of generalizing `sit-rezervo-confgen` to support multiple companies. This change hides the internal logic of the modals, and I opted to make a component for each modal for completeness (even though the `SettingsModal` is mostly just passing props down the tree). However, it does a really nice job hiding complex logic for the `AgendaModal` and `ClassInfoModal`.
=> refactor(index): extract modals to separate components

lib/integration/common.ts, pages/index.tsx, types/rezervo.ts
This PR makes /pages agnostic to integration specific data/functions. This is done by introducing a data structure for storing all our active integrations.
=> chore: introduce data structure for active integration

.eslintrc.js, components/modals/Agenda/Agenda.tsx, components/modals/Agenda/AgendaClassItem.tsx, components/modals/Agenda/AgendaModal.tsx, components/schedule/DaySchedule.tsx, components/schedule/WeekSchedule.tsx, components/schedule/class/ClassCard.tsx, lib/integration/common.ts, types/rezervo.ts
Eslint has had some false positives in the linting, where it marks the arguments for functions passed as arguements as unused. This has been the case in the Typescript definitions of the functions that are passed. With this small fix, we ignore this case, since it is clearly a false positive.
For reference:
https://github.com/eslint/eslint/issues/8661#issuecomment-304531311
=> fix(linting): remove false positive linting

src/lib/integration/adapters.ts, src/lib/popularity.ts, src/types/integration/sit.ts, src/types/rezervo.ts
This field is unused, and does not make sense, since we do not have any info about _a user_ when we fetch the rezervo schedule. Whether the user is in a waiting list and which position it has is done elsewhere, and thus it is redundant to have it here. 
I still think we should keep it in the Sit type however, even though it is not used. This is because the Sit API actually returns a userPosition: null, and I think the integration type should resemble the actual API responses as closely as possible. Open to remove it though, if you have a stance here.
=> refactor(rezervo-type): remove unused userPosition

src/components/modals/ClassInfo/ClassInfo.tsx
The classes in the past already have information about how many people attended as well as how many spots there were available.
=> fix(ClassInfo): hide slot preview if in the past

src/components/modals/ClassInfo/ClassInfo.tsx
Resolves https://github.com/mathiazom/rezervo/issues/20
=> feat(ClassInfoModal): display class weekday

src/components/schedule/WeekNavigator.tsx
Currently, the WeekNavigator maintains the old state for the week offset and week number when switching between integrations. This results in some weird behaviour when the user switches between integrations, while not being on the current week number. This PR resets the state in WeekNavigator completely when the integration is switched, so that it acts more natural.
https://github.com/mathiazom/rezervo-web/assets/26925695/a92135ef-7659-48c9-b5e5-7c0a1cad1c53
https://github.com/mathiazom/rezervo-web/assets/26925695/a78d83a0-36f2-432f-830a-f078f0cf5218
=> fix(WeekNavigator): reset weekOffset and weekNumber on integration switch

src/components/modals/ClassInfo/ClassInfo.tsx, src/components/schedule/class/ClassCard.tsx, src/lib/providers/brpsystems/adapters.ts, src/lib/providers/ibooking/adapters.ts
When there are no instructors, the field in the class info modal should be hidden.
=> feat(schedule): hide instructor fields if no instructors are listed

next.config.js, package.json, yarn.lock
This PR uses a maintained fork of next-pwa, which is the thing most people use these days. Folloeed the [docs](https://ducanh-next-pwa.vercel.app/docs) for installation.
=> build(pwa): use maintained version of next-pwa

src/components/Chain.tsx, src/components/configuration/ConfigBar.tsx, src/components/modals/Agenda/Agenda.tsx, src/components/modals/Agenda/AgendaClassItem.tsx, src/components/modals/Agenda/AgendaModal.tsx, src/components/modals/ChainUser/ChainUserSettings.tsx, src/components/modals/ChainUser/ChainUserSettingsModal.tsx, src/components/modals/ClassInfo/ClassInfo.tsx
This PR does several small things to give the users better feedback about how they have configured the application and what to do in certain situations. I'm open to changing wording/severity etc
1. Make it more obvious that they are logged out. This is done by actually typing out "Logg inn" for the button, and by providing an alert in the class card. I think it makes sense to type out "Logg inn" here, but keep the small logout button. This is because we really want them to log in, not so much logout 😛 
------------------------
2. Indicate that they need to set up a chain user in class info.
------------------------
3. Indicate to the user that booking is inactive, and how to fix it
> I think it makes sense to indicate that booking has been paused in the class info since it might be a …
=> Improve User Feedback

src/components/Chain.tsx
The code to determine whether you have already booked a class only checks whether _someone_ already has booked the class. This can lead to some unexpected behavior:
https://github.com/mathiazom/rezervo-web/assets/26925695/5b604669-f98b-4091-a0cd-a7e43dbe2df5
=> Fix Booking Popup

src/components/modals/ClassInfo/ClassInfo.tsx, src/types/chain.ts
This PR adds a small info banner to visualize any additional information about a class.
Depends on https://github.com/mathiazom/rezervo/pull/36
=> Visualize Additional Class Information

src/components/modals/ClassInfo/ClassInfo.tsx
Hides the "Legg til i timeplan", as well as the slot information. Now it only shows how many slots the class usually has, which is useful information.
=> fix(ClassInfo): hide agenda button and bookings for cancelled classes

src/components/schedule/class/ClassCard.tsx, src/lib/utils/textUtils.ts, src/types/chain.ts
This PR aims to reduce the size of the ClassCard component to make it easier to view more classes at once. This is done by moving the `selectClass` button, so that it is always below the class popularity meter. In addition, I opted to shorten the instructor names, both in terms of how many names we display, as well as shortening their (sometimes chonky) middle names. 
A bit of motivation for this change:
- ClassCards on mobile take up way too much space and make the UI look clunky, not designed for mobile
- iBooking, BRP and Sats are all able to fit more classes into their view at the same time than us
- Minimize the UI difference between a logged in vs logged out user
With these changes, we fit on average 20% more classes into the view than we do today. On mobile that equates to roughly …
=> Reduce ClassCard Size

src/components/modals/Community/Community.tsx, src/components/modals/Community/CommunityUserCard.tsx, src/components/utils/ConfirmationDialog.tsx
Removing friends is quite a destructive action, and thus there should be a confirmation dialog to prevent misclicks.
https://github.com/mathiazom/rezervo-web/assets/26925695/482ee2b7-b5ca-428a-90a9-5753da482150
=> feat(Community): add confirmation dialog when removing friends

src/components/configuration/ConfigBar.tsx, src/components/modals/Profile/Profile.tsx
I have already fat-fingered the logout button a lot of times since the profile icon is now clickable and useful. It also makes more sense to have the logout button on the profile page since that reduces the size of the configbar, which is quite chonky on mobile. The use of the logout button is also super rare for normal users, I feel like it is mostly a thing we use during development.
=> feat(logout): move to profile to avoid misclicks

next.config.js, src/components/modals/BookingPopupModal.tsx, src/components/modals/ClassInfo/ClassInfo.tsx, src/components/schedule/class/ClassCard.tsx, src/components/schedule/class/ClassPopularityMeter.tsx, src/lib/helpers/popularity.ts, src/types/chain.ts
This PR adds the neccecary assets to support the shiny new chain 💪🏻 
Depends on https://github.com/mathiazom/rezervo/pull/43
=> Add Sats Chain 👋

src/components/schedule/class/ClassPopularityMeter.tsx
=> fix(ClassPopularityMeter): add missing () to avoid null text 🤓🕵️

src/components/configuration/ConfigBar.tsx, src/components/schedule/class/ClassCard.tsx
This PR fixes a few small keyboard navigation issues:
- Make profile navigatable by keyboard
- Make the profile have cursor: pointer indicating that it is clickable
- Employ CardActionArea to make cards keyboard navigatable
- CardActionArea also adds a slight tint to classes you hover over, indicating the primary click action, which is neat 🧑‍🔧 
https://github.com/mathiazom/rezervo-web/assets/26925695/5eb28bf7-55db-471a-8e34-2f44249380be
=> feat(a11y): improve keyboard navigation

src/components/modals/ClassInfo/ClassInfo.tsx, src/components/modals/ClassInfo/ClassInfoEntry.tsx
This PR aims to salvage some work from the declined redesign PR.
Since the chip + text on image thing did not work out, I opted to just port over some of the DRY work I did on the component. 
I opted to not bring expandable text, since it does not look that great with my April eyes. 👀 
Supersedes https://github.com/mathiazom/rezervo-web/pull/118
=> refactor(ClassInfo): DRY

src/serviceworker/index.ts
Ref. https://github.com/auth0/nextjs-auth0/issues/1754#issuecomment-2346672593
This resolves our issues with Auth0 not working in Safari (at least on my local machines).
=> HOTFIX(auth0): do not cache Auth0 paths in Serwist

src/components/modals/Agenda/AgendaSession.tsx, src/components/modals/ClassInfo/ClassInfo.tsx, src/types/serialization.ts, src/types/userSessions.ts
This PR displays a user's position in wait lists provided by https://github.com/mathiazom/rezervo/pull/56
~~One note is that immediately after booking, their position is not provided by the backend, since the booking requests do not wait for session pulling before returning. A future improvement could be to extract the booking status/wait list position from each provider's response to a booking request, but I think it is fine to just display the position once session pulling is complete.~~
> Updated. 🚀  See the [latest comment](https://github.com/mathiazom/rezervo-web/pull/137#issuecomment-2111113395)
=> Display Wait List Position

package.json, src/components/Chain.tsx, src/components/modals/ExcludeClassTimeFilters.tsx, src/components/modals/ScheduleFiltersDialog.tsx, src/components/schedule/DaySchedule.tsx, src/components/schedule/WeekNavigator.tsx, src/components/schedule/WeekSchedule.tsx, src/lib/helpers/date.ts, src/lib/helpers/storage.ts, src/pages/_app.tsx, src/types/chain.ts, yarn.lock
Users can add any number of time periods to exclude from their schedules, selecting a weekday, starting and ending times for each. There is validation for the inputs, ensuring that only valid, non-duplicate entries are added. :unicorn: 
See attached screenshots:
=> Add exclude class time filters to hide classes at inconvenient times

src/components/Chain.tsx, src/components/modals/Settings/Settings.tsx, src/components/modals/Settings/SettingsModal.tsx, src/components/utils/PWAInstallPrompt.tsx, src/lib/helpers/storage.ts, src/pages/index.tsx
Currently, the install instructions for the PWA are only on the index page, and thus inaccessible if the user has already clicked one of the branches. (since we always redirect from the index once the users have selected a branch) This is a problem if those users want to install the app, as there is no easy way for them to see the instructions again. 
This PR adds an info box with a button in Settings that triggers the PWA install prompt. This info is only visible if the user has not installed the PWA.
This feature is a useful nudge for users to actually install rezervo as an app, and not just use it as a website. That way, they will hopefully enable push notifications and get fully integrated into the rezervo ecosystem 🤗 
https://github.com/mathiazom/rezervo-web/assets/26925695/cfaea547-f …
=> Add PWA Install Button to Settings

src/components/modals/Agenda/Agenda.tsx, src/components/modals/ClassInfo/ClassInfo.tsx, src/components/modals/Community/Community.tsx, src/components/modals/ModalWrapper.tsx, src/components/modals/Profile/Profile.tsx, src/components/modals/Settings/CalendarFeed.tsx, src/components/modals/Settings/Memberships/Memberships.tsx, src/components/modals/Settings/PushNotifications.tsx, src/components/modals/Settings/Settings.tsx, src/components/modals/Settings/SwitchWrapper.tsx, src/components/modals/SubHeader.tsx
This PR extracts common markup for the modals to reduce duplication. These bits of code have been copy-pasted over and over, and we really should have extracted them earlier 🤠 
These new components keep the design very similar to before, with slight changes due to the standardization of components where our original code differs slightly.
=> Extract Common Modal Components To Reduce Duplication

src/components/Chain.tsx, src/components/modals/ExcludeClassTimeFilters.tsx, src/components/modals/ScheduleFiltersDialog.tsx, src/components/schedule/DaySchedule.tsx, src/components/schedule/WeekNavigator.tsx, src/components/schedule/WeekSchedule.tsx, src/lib/helpers/date.ts, src/lib/helpers/storage.ts, src/types/chain.ts
Current "Exclude class time"-filter page:
New "Exclude class time"-filter page:
Details are hidden when the entire filter is disabled:
=> feat: add enable flag for exclude class time filters
