mathiazom/rezervo-web

- config/config.ts
- lib/iBooking.ts
- pages/index.tsx
Now actually up to date 🐌 ➡️ 🚤
> feat: static site generation

- pages/index.tsx
Remove the double scrollbar, by adjusting the size of the Schedule container
> style: fix double scrollbar

- components/Integration.tsx
- components/schedule/WeekNavigator.tsx
- components/schedule/WeekSchedule.tsx
- lib/integration/fsc.ts
- lib/integration/sit.ts
- pages/api/schedule.ts
- pages/fsc.tsx
- pages/index.tsx
- types/integration/fsc.ts
- types/rezervo.ts
With this PR, I introduce a RezervoSchedule type. This type currently only contains SitWeekSchedule[] offset by weeks. Soon however, this will have its own type. Also did some refactoring to make the migration more smooth.
> Introduce RezervoSchedule type

- components/Integration.tsx
- components/schedule/DaySchedule.tsx
- components/schedule/WeekNavigator.tsx
- components/schedule/WeekSchedule.tsx
- config/config.ts
- lib/integration/adapters.ts
- lib/integration/common.ts
- lib/integration/sit.ts
- lib/popularity.ts
- pages/api/schedule.ts
- pages/index.tsx
- types/rezervo.ts
With this PR, I prepare for the ascension into ultimate independency for Rezervo. Now, we go all the way down to RezervoDaySchedule, which currently has SitClasses. This will be changed to RezervoClasses in the future. 🎸
> Introduce RezervoWeekSchedule and RezervoDaySchedule 👋

- components/Integration.tsx
- components/configuration/ConfigBar.tsx
- components/modals/Agenda/Agenda.tsx
- components/modals/Agenda/AgendaClassItem.tsx
- components/modals/Agenda/AgendaModal.tsx
- components/modals/ClassInfo/ClassInfo.tsx
- components/modals/ClassInfo/ClassInfoModal.tsx
- components/schedule/DaySchedule.tsx
- components/schedule/WeekSchedule.tsx
- components/schedule/class/ClassCard.tsx
- components/schedule/class/ClassPopularityMeter.tsx
- lib/integration/adapters.ts
- lib/integration/common.ts
- lib/integration/sit.ts
- lib/popularity.ts
- types/integration/sit.ts
- types/rezervo.ts
With this PR, I port the SitClass properties over to a custom RezervoClass type. This type if due to be changed in the future, but I felt it would be clean to just port everything over in the first place, then make changes to the type as we see fit. I also made the adapter from sit to rezervo types more explicit to make it easier to make modifications later and to only have the key-values we explicitly define.
> Introduce RezervoClass type

- .eslintrc.js
- components/Integration.tsx
- components/configuration/ConfigBar.tsx
- components/configuration/MobileConfigUpdateBar.tsx
- components/modals/Agenda/Agenda.tsx
- components/modals/Agenda/AgendaClassItem.tsx
- components/modals/Agenda/AgendaModal.tsx
- components/modals/ClassInfo/ClassInfo.tsx
- components/modals/ClassInfo/ClassInfoModal.tsx
- components/modals/Settings/CalendarFeed.tsx
- components/modals/Settings/Settings.tsx
- components/modals/Settings/SettingsModal.tsx
- components/schedule/DaySchedule.tsx
- components/schedule/WeekNavigator.tsx
- components/schedule/WeekSchedule.tsx
- components/schedule/class/ClassCard.tsx
- components/schedule/class/ClassPopularityMeter.tsx
- components/schedule/class/ClassUserAvatar.tsx
- components/schedule/class/ClassUsersAvatarGroup.tsx
- components/utils/ConfirmationDialog.tsx
- lib/integration/common.ts
- lib/integration/fsc.ts
- lib/integration/sit.ts
- lib/popularity.ts
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/api/schedule.ts
- pages/index.tsx
- yarn.lock
This PR adds:
- Linting of imports
- Automatic sorting of imports
> Add Linting For Imports

- pages/404.tsx
The default 404 page made me sad 🧹
> Add Custom 404 Page

- .env.local.example
- Dockerfile
- README.md
- docker-compose.dev.yml
- docker-compose.template.yml
- Use Node 18 in the Dockerfile and copy env variables
- Add docker compose dev file
- Update readme to cover setup and be in line with rezervo
> Update Build Configuration

- .gitignore
- next.config.js
- src/lib/integration/adapters.ts
- src/lib/integration/common.ts
- src/lib/integration/fsc.ts
- src/types/integration/fsc.ts
- src/types/rezervo.ts
With this PR I do the following:
- Add a helper that provides default categories and colors based on activity names. I use this helper to give FSC classes more lively colors.
- Add description and image to FSC classes
- Some minor fixups: (remove extra duration info from activityName, ignore some pwa files and fix an interface)
> Improve Data Quality And Display Of FSC Data

- src/components/modals/Agenda/Agenda.tsx
- src/components/utils/DateTimeProvider.tsx
- src/lib/consts.ts
- src/lib/helpers/date.ts
- src/lib/integrations/fsc/adapters.ts
- src/lib/integrations/fsc/fetchers.ts
- src/lib/integrations/sit/adapters.ts
- src/lib/integrations/sit/fetchers.ts
- src/lib/serialization/deserializers.ts
- src/pages/_app.tsx
- refactor(DateTime): set locale and time zone globally
- refactor(helpers/date): inline getDateTime
- refactor(helpers/date): introduce helper for getting capitalized weekdays
> Setup Global Date Configuration

- .env.local.example
- src/components/modals/Settings/PushNotifications.tsx
- src/components/modals/Settings/Settings.tsx
- src/lib/hooks/usePushNotificationSubscription.ts
- src/lib/utils/base64Utils.ts
- src/pages/api/notifications/push.ts
- src/pages/api/notifications/push/verify.ts
This PR sets up push notification support for rezervo-web. Currently, the push notifications are sent from the rezervo-web API, since I was not able to get pywebpush to work.
Depends on: https://github.com/mathiazom/rezervo/pull/17
> feat: push notifications

- src/components/schedule/class/ClassCard.tsx
Resolves https://github.com/mathiazom/rezervo-web/issues/33
> fix(ClassCard): hide animation if class is in the past

- package.json
- yarn.lock
TS 5.2 has some pretty nice DX features, and is non breaking. Also bumped minor versions of other devDeps for convenience.
> build(deps): bump TS and other devDeps

- src/components/modals/ClassInfo/ClassInfo.tsx
- src/components/schedule/class/ClassCard.tsx
- src/components/schedule/class/ClassPopularityMeter.tsx
- src/lib/providers/brpsystems/adapters.ts
- src/lib/providers/ibooking/adapters.ts
- src/lib/providers/ibooking/types.ts
- src/types/integration.ts
This PR gives the user feedback when a class has been cancelled in the schedule
> feat(schedule): indicate when a class has been cancelled

- package.json
- src/app/api/[integration]/all-configs/route.ts
- src/app/api/[integration]/book/route.ts
- src/app/api/[integration]/cancel-booking/route.ts
- src/app/api/[integration]/config/route.ts
- src/app/api/[integration]/schedule/route.ts
- src/app/api/[integration]/sessions/route.ts
- src/app/api/[integration]/user/route.ts
- src/app/api/cal-url/route.ts
- src/app/api/features/route.ts
- src/app/api/notifications/push/public-key/route.ts
- src/app/api/notifications/push/route.ts
- src/app/api/notifications/push/verify/route.ts
- src/app/api/preferences/route.ts
- src/app/api/revalidate/route.ts
- src/lib/helpers/api.ts
- src/lib/hooks/usePushNotificationSubscription.ts
- yarn.lock
- refactor(api): use NextResponse => Reponse if possible
- refactor(next): bump to v13.5
> Simplify API and Bump NextJS

- src/components/Chain.tsx
- src/components/modals/BookingPopupModal.tsx
- src/components/modals/ClassInfo/ClassInfo.tsx
- src/components/utils/ConfirmationDialog.tsx
It displays a popup asking if you would like to book the first occurrence of that class   
It displays a popup asking if you would like to cancel that class
https://github.com/mathiazom/rezervo-web/assets/26925695/55ad54a0-ca4b-45d4-b777-b7a5d9037101
> Add Booking Popup to Book/Cancel When The Agenda Is Modifed

- src/components/modals/ChainUser/ChainUserSettings.tsx
- src/components/modals/ChainUser/ChainUserSettingsModal.tsx
- src/lib/hooks/useChainUser.ts
This PR handles rejected authentication when a user tries to log into their chain user account.
Depends on: https://github.com/mathiazom/rezervo/pull/35
https://github.com/mathiazom/rezervo-web/assets/26925695/dcff2681-d1f1-44a9-9810-107c00ff398b
> Handle Authentication Errors When Trying to Log Into Chain User

- src/components/modals/ClassInfo/ClassInfo.tsx
- src/types/chain.ts
Depends on https://github.com/mathiazom/rezervo/pull/40
> feat(ClassInfo): display cancellation text if present

- src/app/api/community/relationship/route.ts
- src/app/api/community/route.ts
- src/app/api/community/update-relationship/route.ts
- src/components/Chain.tsx
- src/components/configuration/ConfigBar.tsx
- src/components/modals/Community/Community.tsx
- src/components/modals/Community/CommunityModal.tsx
- src/components/modals/Community/CommunityUserCard.tsx
- src/lib/hooks/useCommunity.ts
- src/lib/theme.ts
- src/types/community.ts
This PR sets up the community functionality.
The following features are supported:
- Send friend requests
- Accept/Deny friend requests
- Remove friends
- Send push notifications to the receivers of friend requests
- In addition, you now only see your own and your friends  configs and sessions
Here is a little showcase:
https://github.com/mathiazom/rezervo-web/assets/26925695/150a09a1-67c2-4311-804d-0b20c30f44e5
Depends on https://github.com/mathiazom/rezervo/pull/33
> Set Up Community Modal

- src/app/api/user/route.ts
- src/lib/helpers/api.ts
- src/lib/hooks/useChainUser.ts
- src/lib/hooks/usePreferences.ts
- src/lib/hooks/usePushNotificationSubscription.ts
- src/lib/hooks/useUserConfig.ts
- src/lib/utils/fetchUtils.ts
Small refactorings to improve typings a bit. Basically: remove `any`s
> refactor: improve fetcher types

- src/components/Chain.tsx
- src/components/modals/CategoryFilters.tsx
- src/components/modals/LocationFilters.tsx
- src/components/modals/ScheduleFiltersDialog.tsx
- src/components/schedule/WeekNavigator.tsx
- src/lib/helpers/fetchers.ts
- src/types/chain.ts
- src/types/serialization.ts
> This PR depends on https://github.com/mathiazom/rezervo/pull/42. Without it, the checkboxes look a bit 💩
> Add Category Color Hints to Filters

- src/app/api/[chain]/schedule/route.ts
- src/components/Chain.tsx
- src/lib/helpers/date.ts
- src/lib/helpers/fetchers.ts
- src/lib/hooks/useSchedule.ts
- src/lib/serialization/deserializers.ts
- src/lib/serialization/serializers.ts
- src/pages/[chain].tsx
- src/types/chain.ts
- src/types/serialization.ts
This PR removes the usage of weekOffset, in favor of the novel compact ISO week, used in the query params.
> Obliterate Week Offset

- src/components/Chain.tsx
- src/components/modals/ModalWrapper.tsx
- src/components/utils/CheckIn.tsx
- src/lib/helpers/storage.ts
- src/types/chain.ts
https://github.com/user-attachments/assets/8c667aeb-7cb1-4ee7-a4a1-886f73ae6331
> feat: CheckIn component

- src/components/modals/Settings/Memberships/MembershipLoginModal.tsx
- src/lib/hooks/useChainUser.ts
Adds the option to be able to destroy a chain user member ship. Updated the UI of the login modal too to make it more apparent that you have already logged in.
I opted to not do an additional confirmation dialog on the logout button, since you would have to explicitly open the edit chain user modal to get there in the first place. (which is somewhere you usually do not go). Also it would be a triple modal. 🤠
> feat: option to destroy chain user
